variables:
- group: tmp_particle

trigger:
- master
- feature/*

pool:
  vmImage: 'macOS-10.14'

steps:
- task: NodeTool@0
  displayName: 'environment'

- script:
    npm install --global particle-cli
  displayName: 'configuration'

- script:
    particle login --username $(PARTICLE) --password $(PARTICLE_)
  displayName: '...'

- script:
    particle compile argon --target 0.9.0 --saveTo $(Build.ArtifactStagingDirectory)/tmp.firmware.bin
  displayName: 'firmware'

- task: GitHubRelease@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'release'
  inputs:
    gitHubConnection: undefinedTea
    tagSource: manual
    tag: $(Build.BuildNumber)
    assets: $(Build.ArtifactStagingDirectory)/tmp.firmware.bin
